language: node_js
node_js:
  - "6"

branches:
  only:
    - master
    
install:
  - export GOPATH=$HOME/go
  - export PATH=$GOPATH/bin:$PATH
  - go get -u -v github.com/spf13/hugo
  - npm -g install firebase-tools
  - npm install

script:
  - npm run build

after_success:
  - firebase deploy --token=${FIREBASE_API_TOKEN}
