language: node_js
node_js:
  - "6"

branches:
  only:
    - master

before_install:
  - git submodule sync
  - git submodule update --init --recursive

install:
  - export GOPATH=$HOME/go
  - export PATH=$GOPATH/bin:$PATH
  - go get -u -v github.com/spf13/hugo && hugo version
  - npm -g install firebase-tools
  - npm install

after_install:
  - ls -R themes

script:
  - npm run build

after_success:
  - firebase deploy --token=${FIREBASE_API_TOKEN}
