baseurl = "https://blog.lacolaco.net/"
languageCode = "ja-JP"
title = "<output type=\"laco\">"
theme = "beautifulhugo"
googleAnalytics = "UA-52362663-4"
disqusShortName = "blog-lacolaco"

[blackfriday]
  angledQuotes = false
  fractions = false
  hrefTargetBlank = true
  plainIDAnchors = true
  # extensions = ["hardLineBreak"]

[Params]
  logo = "img/icon.png"
  ogImage = "//blog.lacolaco.net/assets/images/icon.png"
  subtitle = "JavaScript, Web, Angular"

[Author]
  name = "Laco"
  github = "laco0416"
  twitter = "laco0416"
  
[[menu.main]]
    name = "lacolaco.net"
    weight = -100
    identifier = "about"
    url = "https://lacolaco.net/"
 
[[menu.main]]
    name = "RSS"
    weight = 1
    identifier = "rss"
    url = "/index.xml"
